import { db } from '../src/lib/db';
import crypto from 'crypto';

async function main() {
  // Hash for 'password123' generated by Better-Auth
  const sampleAccount = await db.account.findFirst({
    where: { providerId: 'credential', password: { not: null } }
  });

  if (!sampleAccount || !sampleAccount.password) {
    console.error('No sample credential account found to clone hash from');
    return;
  }

  const passwordHash = sampleAccount.password;

  const emailsToSeed = [
    'citizen@test.in',
    'admin@test.in',
    'officer@test.in',
    'manager@test.in',
    'citizen.lifecycle@pothole.in',
    'officer.lifecycle@pothole.in',
    'manager.lifecycle@pothole.in',
    'admin.lifecycle@pothole.in'
  ];

  for (const email of emailsToSeed) {
    const user = await db.user.findUnique({ where: { email } });
    if (user) {
      const existing = await db.account.findFirst({
        where: { userId: user.id, providerId: 'credential' }
      });
      if (!existing) {
        await db.account.create({
          data: {
            id: crypto.randomBytes(16).toString('hex'),
            userId: user.id,
            accountId: user.id,
            providerId: 'credential',
            password: passwordHash
          }
        });
        console.log(`Successfully created password 'password123' for ${email}`);
      } else {
        await db.account.update({
          where: { id: existing.id },
          data: { password: passwordHash }
        });
        console.log(`Updated password 'password123' for ${email}`);
      }
    }
  }
}

main().then(() => process.exit(0)).catch(console.error);
